# Auto-generated by compose2nix.

{
  pkgs,
  lib,
  config,
  ...
}:

{
  options = {
    gaming.enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Enable gaming-specific configurations.";
    };
  };

  config = lib.mkIf config.gaming.enable {

    # Containers
    virtualisation.oci-containers.containers."calibre-web-automated" = {
      image = "crocodilestick/calibre-web-automated:latest";
      environment = {
        "HARDCOVER_TOKEN" = "your_hardcover_api_key_here";
        "NETWORK_SHARE_MODE" = "false";
        "PGID" = "1000";
        "PUID" = "1000";
        "TZ" = "America/New_York";
      };
      volumes = [
        "/home/howard/calibre-web-automated/config:/config:rw"
        "/home/howard/calibre-web-automated/ingest:/cwa-book-ingest:rw"
        "/home/howard/calibre-web-automated/library:/calibre-library:rw"
        "/home/howard/calibre-web-automated/plugins:/config/.config/calibre/plugins:rw"
      ];
      ports = [
        "8083:8083/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=calibre-web-automated"
        "--network=calibre-web-automated_default"
      ];
    };
    systemd.services."podman-calibre-web-automated" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
      };
      after = [
        "podman-network-calibre-web-automated_default.service"
      ];
      requires = [
        "podman-network-calibre-web-automated_default.service"
      ];
      partOf = [
        "podman-compose-calibre-web-automated-root.target"
      ];
      wantedBy = [
        "podman-compose-calibre-web-automated-root.target"
      ];
    };

    # Networks
    systemd.services."podman-network-calibre-web-automated_default" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f calibre-web-automated_default";
      };
      script = ''
        podman network inspect calibre-web-automated_default || podman network create calibre-web-automated_default
      '';
      partOf = [ "podman-compose-calibre-web-automated-root.target" ];
      wantedBy = [ "podman-compose-calibre-web-automated-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-calibre-web-automated-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };
}
